### ISSUE TITLE
Style in html

### ISSUE THREAD

**Issue by anoukbruinn** [KaanKalmi/fix-the-flow-ui-events#3]
Als je veel hetzelfde in je style.css hebt staan kwa styling en bijvoorbeeld alleen de kleur veranderd, probeer dan de styling op alle elementen tegelijk te zetten behalve de keur. Deze kun je in de html zelf toevoegen als style element.

**Comment by KaanKalmi** [comment]
![image](https://github.com/KaanKalmi/fix-the-flow-ui-events/assets/144000125/2724a27e-5f91-443c-948f-9627fc047fb3)

Dit ook goed?

**Comment by anoukbruinn** [comment]
ja !
